
tasks:
  - init: yarn
    command: |
      export HRM_HOST=`gp url 3000`
      yarn dev

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true